server:
  port: 5000

# url de connexion à la base de données
spring:
  h2:
    console.enabled: true #pour afficher la console H2
  datasource:
    url: jdbc:h2:mem:testdb #url
    driverClassName: org.h2.Driver #driver
    username: sa #username
    password: password #password
  jpa:
    show-sql: true # affiche les requêtes sql générées dans la console
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

## App Properties
app:
  jwtSecret: 9a02115a835ee03d5fb83cd8a468ea33e4090aaaec87f53c9fa54512bbef4db8dc656c82a315fa0c785c08b0134716b81ddcd0153d2a7556f2e154912cf5675f
  jwtExpirationInMs: 604800000