spring:
  application:
    name: config-server-client
  profiles:
    active: development
  config:
    import: configserver:http://localhost:8888

management:
  endpoints:
    web:
      exposure:
        include: "*"