server.port: 8888
# config via Git et Github
# spring.cloud.config.server.git.uri: file://Users/aurelienpietrzak/Documents/CoursFac/architecture-distribuee/config-repo

# config via un dossier en local sans utiliser git et github
spring.profiles.active: native
spring.cloud.config.server.native.searchLocations: file:///Users/aurelienpietrzak/Documents/CoursFac/architecture-distribuee/config-repo-native